### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Pickpate** [Doubiiu/DynamiCrafter#117]
Could you please add an license for your model in huggingface? Or state that the license  (Apache 2.0) for this project cover the model？

**Comment by Doubiiu** [comment]
Done.

**Comment by Pickpate** [comment]
Thanks for that. I notice that you spicify that the Apache 2.0 license cover source code. And there isn't an license for the model in Huggingface, it seems that the models within this project are research purpose only, am I right?

**Comment by Pickpate** [comment]
Hi I notice you have add license file(Apache 2.0) in huggingface repo, while there still isn't a license lable for the model and some of the model cards say that the model is for research purpose. So I think you mean the [DynamiCrafter]models are licensed under Apache 2.0, am I right?

**Comment by Doubiiu** [comment]
Yeah. The model and code are under Apache 2.0.

**Comment by Pickpate** [comment]
Thanks for that！
